### ISSUE TITLE
Switch to H3 hex grid

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1341]
We currently use the `honeycomb` library for hex-cell support.

But, this library does not understand global map projections - so it can only really be used on a locally flat Earth.

However, the h3 library from Uber supports geographic projections out of the box, and would be better suited to large-scale wargames.

* [x] include h3 (with TypeScript wrappers) in the build
* [x] add new coordinate data types - to store h3 coords in parallel with honeycomb coords
* [x] create new map bounds data type that gives data required for h3 (bounds, resolution, origin)
* [x] add new wargame bounds to existing Atlantic test data
* [x] switch hex grid rendering to h3 rendering
* [x] modify `mapping\index.tsx` to use new h3 logic
* [x] modify `hex-grid\index.tsx` to use new h3 logic
* [x] modify atlantic wargame to introduce coords for new grid system
* [x] modify `canCombineWith` to use h3 cell comparison
* [x] check atlantic wargame runs
* [x] deprecate old hex grid & grid definition logic
* [ ] load new h3 layer data (terrain-type)
* [ ] load new h3 polygon data
* [x] Provide wargame covering small area

## To-do items
* [x] Fix `can-combine-with` tests
* [ ] Put back `hex-grid\index.ts` tests for terrain
