### ISSUE TITLE
Force Laydown for both Umpire & Players

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1587]
When designing a game, if the Game Designer adds any assets, their initial locations need to be set.  This _could_ be implemented by the Game Designer entering the (horrible) hex coord.  But, it's easier to create the assets, and then arrange them via drag/drop within the game itself (before game initiated).

![image](https://user-images.githubusercontent.com/1108513/172350076-546a7326-6ee8-41b8-bd88-37c147b2464a.png)

Also, for some wargames, the Game Designer may let player(s) specify the initial positions for some assets.

![image](https://user-images.githubusercontent.com/1108513/172350144-44013132-5ce9-458e-b8ec-5b9761f29e6b.png)

### Location Pending pen
We need to think through the UX for both - including where we locate the "pending" assets. After all, they don't have an initial area.  One solution is to have a box at the top-left, with one un-placed asset per cell.  The GD or player drags the asset from there to the desired location.

Maybe think of a better name than `location pending pen`, too.

### Laydown phases:
1. Game Design (game not initialised)
2. Umpire laydown (game initialised, one or more assets set to `Force laydown`)
3. Player laydown (game initialised, no assets set to `Force laydown`, one or more set to `Player laydown`)
4. Game-play (game initialised, no assets set to `Force laydown` or `Player laydown`)

### Tasks: 
* [x] Allow game designer to set laydown/initial location in admin pages (Almost complete)
* [x] Logic to decide which laydown phase we're in. See `laydownPhaseFor()`
* [x] _Somehow_ make Game Designer (or players) aware of which laydown phase we're in.
* [x] Allow routes to be generated for assets that don't have a position or location
* [x] Logic to let the `asset-icons` component decide where to put the _Pen_, render the pen, and also create positions/locations for the `asset-icon` component to use
* [x] Logic to allow player to drag/drop pending assets
* [x] Logic to submit laydown positions

**Comment by ShendMikullovci** [comment]
I think adding another icon for pending icons may be a little too much. We've already got a loaded screen including assets, markers (both singular and composites), buttons/features.

I have two ideas:

1. Pending assets are shown in their same icon and color, except slightly grayed and in reduced opacity (approx. 50%). The transparency should emphasize its ephemeral state, as we've been conditioned to view gray/transparent as inconclusive in games.
2. Have the assets (either in full or reduced opacity) blink on the pending laydown spot. This, however, attracts more attention and adds a feel of urgency to the laydown, which I'm not sure we want (?).

We could chop this up in 3 different phases for the GD/Players to know: 

- Blink at 50% Opacity: Asset location pending.
- 50% Opacity Only: Asset location selected but to be confirmed. 
- 100% Opacity: Asset location selected and confirmed.

**Comment by IanMayo** [comment]
Thanks for that @ShendMikullovci 

There is an example of blinking images here: http://jsfiddle.net/rameezrami/27754r4f/1/

The above example uses an animated blinking - so they remain visible for most of the time.

**Comment by ShendMikullovci** [comment]
Just ran a test on this. Here's how it could look: 

https://user-images.githubusercontent.com/85491794/174756305-9d769227-d372-4e8f-8276-d1b5a373e04f.mp4

Obviously, we can play around with the delay, opacity and other settings. I think this looks promising. Let me know how you feel about it.
